name: Build Xiaomi Sagit exTHmui
on: 
  release:
    types: [published]
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libwxgtk3.0-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Install repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        sudo cp ~/bin/repo /bin/repo
        sudo chmod a+x /bin/repo
        
    - name: Config Git
      run: git config --global user.email "dzg1728339222@live.cn.com"
           git config --global user.name "lollipop907"a

    - name: Load custom configuration
      run: |
        repo init -u https://github.com/exthmui/android.git -b exthm-10
        repo init -u https://github.com/exthmui/android.git -b exthm-10 --depth=1

    - name: Sync
      run: |
        repo sync [-j8 --fail-fast --force-sync]
    - name : Build
      uses: . build/envsetup.sh
            lunch exthm_segit-userdebug
            breakfast segit
 
        name: bulid
        path: mka bacon
  
  
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Sagit
        path: ./android/bin
      
